import type { Metadata } from 'next'
import './globals.css'

import '@mantine/core/styles.css'

import { ColorSchemeScript, MantineProvider } from '@mantine/core'
import { Header } from './components/Header'
import * as font from '../fonts/fonts'
import { ThemeProvider } from 'next-themes'
import SideNav from './components/SideNav'
import ClientProvider from './ClientProvider'
import { AuthWrapper } from './AuthWrapper'
import { cookies } from 'next/headers'

export const metadata: Metadata = {
	title: 'lumine',
	description: 'Generated by create next app',
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	const token = cookies().get('refreshToken')?.value

	if (!token) {
		return (
			<html lang='en'>
				<head>
					<ColorSchemeScript />
				</head>
				<body
					className={`${font.geistSans.variable} ${font.geistMono.variable} ${
						font.helvetica_bold.variable
					} ${font.helvetica_regular.variable} antialiased mx-auto`}>
					<ClientProvider>
						<ThemeProvider defaultTheme='dark'>
							<MantineProvider defaultColorScheme='dark'>
								{/* <AuthWrapper> */}
									{children}
								{/* </AuthWrapper> */}
							</MantineProvider>
						</ThemeProvider>
					</ClientProvider>
				</body>
			</html>
		)
	}

	return (
		<html lang='en'>
			<head>
				<ColorSchemeScript />
			</head>
			<body
				className={`${font.geistSans.variable} ${font.geistMono.variable} ${
					font.helvetica_bold.variable
				} ${font.helvetica_regular.variable} antialiased mx-auto max-w-[1224px]`}>
				<ClientProvider>
					<ThemeProvider defaultTheme='dark'>
						<MantineProvider defaultColorScheme='dark'>
							<AuthWrapper token={token}>
								<Header />
								<main className={`pt-[120px] ${token ? 'block' : 'hidden'}`}>
									<SideNav />
									<div className='pl-[290px]'>
										{children}
									</div>
								</main>
							</AuthWrapper>
						</MantineProvider>
					</ThemeProvider>
				</ClientProvider>
			</body>
		</html>
	)
}
